# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: media.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmedia.proto\x12\x05media\"4\n\x0cMediaRequest\x12\x10\n\x08media_id\x18\x01 \x01(\t\x12\x12\n\nmedia_type\x18\x02 \x01(\t\"7\n\rMediaResponse\x12\x12\n\nmedia_data\x18\x01 \x01(\x0c\x12\x12\n\nmedia_type\x18\x02 \x01(\t2J\n\x0cMediaService\x12:\n\rDownloadMedia\x12\x13.media.MediaRequest\x1a\x14.media.MediaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIAREQUEST']._serialized_start=22
  _globals['_MEDIAREQUEST']._serialized_end=74
  _globals['_MEDIARESPONSE']._serialized_start=76
  _globals['_MEDIARESPONSE']._serialized_end=131
  _globals['_MEDIASERVICE']._serialized_start=133
  _globals['_MEDIASERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
