@startuml
|User|
start
:Clicks on forgot password;

|Frontend|
:redirect user to forgot password page;
repeat
repeat
:asks for user email address;

|User|
:enter email address;


|Frontend|
:check user email address format;
backward: Notify user about email address format is wrong;
repeat while (email address format is good ?) is (no) not (yes)
:send a forgot password request to IAM Service;

|IAM Service|
:check user email address;
|Frontend|
backward: Notify user about email address is not found;
repeat while (email address exists) is (no) not (yes)
  ->
 repeat
|IAM Service|
:send a 5 minutes OTP code to user email;
:inform fronted OTP sent;

|Frontend|
:ask user for OTP code with 5 minutes timer;
:provide an option to resend OTP after 5 minutes;

repeat
|User|
if (user action) then (Resend OTP)
    |Frontend|
    if (5 minutes timer finished) then (yes)
        :send a new OTP request to IAM service;
    else (no)
        :keep resend otp disabled until 5 minutes timer finishes;
    end if

else (Enters OTP)
    |Frontend|
    :send OTP to IAM service;
end if
    |IAM Service|
    :check OTP;
    |Frontend|
    backward: Notify user OTP is invalid;
    repeat while (is OTP valid ?) is (no)


|Frontend|
:redirect user to reset password page;
repeat
:ask user for new password and confirm new password;

|User|
:Enter new password & confirm password;

|Frontend|
:Check password format;
:Check password & confirm password are the same;
backward: Notify user about password format or password mismatch;
repeat while (passwords are good) is (no) not (yes)
->
:send an update password request for user to IAM service;

|IAM Service|
:Update user password;
:inform fronted user password changed;

|Frontend|
:inform user about password successfully changed;
:redirect user to login page;
end
@enduml
